# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'addConv.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_AddCon(object):
    def setupUi(self, AddCon):
        AddCon.setObjectName("AddCon")
        AddCon.resize(582, 214)
        self.filterLabel = QtWidgets.QLabel(AddCon)
        self.filterLabel.setGeometry(QtCore.QRect(30, 50, 54, 12))
        self.filterLabel.setObjectName("filterLabel")
        self.kernelSizeLabel = QtWidgets.QLabel(AddCon)
        self.kernelSizeLabel.setGeometry(QtCore.QRect(190, 50, 101, 16))
        self.kernelSizeLabel.setObjectName("kernelSizeLabel")
        self.stridesLabel = QtWidgets.QLabel(AddCon)
        self.stridesLabel.setGeometry(QtCore.QRect(390, 50, 71, 16))
        self.stridesLabel.setObjectName("stridesLabel")
        self.activationLabel = QtWidgets.QLabel(AddCon)
        self.activationLabel.setGeometry(QtCore.QRect(210, 110, 91, 16))
        self.activationLabel.setObjectName("activationLabel")
        self.paddingLabel = QtWidgets.QLabel(AddCon)
        self.paddingLabel.setGeometry(QtCore.QRect(30, 110, 61, 16))
        self.paddingLabel.setObjectName("paddingLabel")
        self.filterEdit = QtWidgets.QLineEdit(AddCon)
        self.filterEdit.setGeometry(QtCore.QRect(90, 50, 91, 20))
        self.filterEdit.setObjectName("filterEdit")
        self.kernelSizeEdit = QtWidgets.QLineEdit(AddCon)
        self.kernelSizeEdit.setGeometry(QtCore.QRect(290, 50, 91, 20))
        self.kernelSizeEdit.setObjectName("kernelSizeEdit")
        self.stridesEdit = QtWidgets.QLineEdit(AddCon)
        self.stridesEdit.setGeometry(QtCore.QRect(460, 50, 101, 20))
        self.stridesEdit.setObjectName("stridesEdit")
        self.paddingComboBox = QtWidgets.QComboBox(AddCon)
        self.paddingComboBox.setGeometry(QtCore.QRect(100, 110, 91, 22))
        self.paddingComboBox.setObjectName("paddingComboBox")
        self.activationComboBox = QtWidgets.QComboBox(AddCon)
        self.activationComboBox.setGeometry(QtCore.QRect(310, 110, 91, 22))
        self.activationComboBox.setEditable(False)
        self.activationComboBox.setCurrentText("")
        self.activationComboBox.setObjectName("activationComboBox")
        self.continueButton = QtWidgets.QPushButton(AddCon)
        self.continueButton.setGeometry(QtCore.QRect(320, 170, 81, 31))
        self.continueButton.setObjectName("continueButton")
        self.cancelButton = QtWidgets.QPushButton(AddCon)
        self.cancelButton.setGeometry(QtCore.QRect(180, 170, 81, 31))
        self.cancelButton.setObjectName("cancelButton")

        self.retranslateUi(AddCon)
        QtCore.QMetaObject.connectSlotsByName(AddCon)

    def retranslateUi(self, AddCon):
        _translate = QtCore.QCoreApplication.translate
        AddCon.setWindowTitle(_translate("AddCon", "Add Convolution"))
        self.filterLabel.setText(_translate("AddCon", "filters"))
        self.kernelSizeLabel.setText(_translate("AddCon", "kernel_size"))
        self.stridesLabel.setText(_translate("AddCon", "strides"))
        self.activationLabel.setText(_translate("AddCon", "activation"))
        self.paddingLabel.setText(_translate("AddCon", "padding "))
        self.continueButton.setText(_translate("AddCon", "确定"))
        self.cancelButton.setText(_translate("AddCon", "取消"))
        paddingList = ["VALID","SAME"]
        self.paddingComboBox.addItems(paddingList)
        activationList = ["Sigmoid","ReLU","Tanh","softmax"]
        self.activationComboBox.addItems(activationList)
