# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'addFullConnect.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_addFC(object):
    def setupUi(self, addFC):
        addFC.setObjectName("addFC")
        addFC.resize(324, 231)
        self.unitsLabel = QtWidgets.QLabel(addFC)
        self.unitsLabel.setGeometry(QtCore.QRect(50, 60, 51, 16))
        self.unitsLabel.setObjectName("unitsLabel")
        self.activationLabel = QtWidgets.QLabel(addFC)
        self.activationLabel.setGeometry(QtCore.QRect(20, 100, 91, 16))
        self.activationLabel.setObjectName("activationLabel")
        self.unitsEdit = QtWidgets.QLineEdit(addFC)
        self.unitsEdit.setGeometry(QtCore.QRect(120, 60, 172, 21))
        self.unitsEdit.setObjectName("unitsEdit")
        self.activationComboBox = QtWidgets.QComboBox(addFC)
        self.activationComboBox.setGeometry(QtCore.QRect(120, 100, 171, 22))
        self.activationComboBox.setEditable(False)
        self.activationComboBox.setCurrentText("")
        self.activationComboBox.setObjectName("activationComboBox")
        self.continueButton = QtWidgets.QPushButton(addFC)
        self.continueButton.setGeometry(QtCore.QRect(160, 160, 81, 31))
        self.continueButton.setObjectName("continueButton")
        self.cancelButton = QtWidgets.QPushButton(addFC)
        self.cancelButton.setGeometry(QtCore.QRect(60, 160, 81, 31))
        self.cancelButton.setObjectName("cancelButton")

        self.retranslateUi(addFC)
        QtCore.QMetaObject.connectSlotsByName(addFC)

    def retranslateUi(self, addFC):
        _translate = QtCore.QCoreApplication.translate
        addFC.setWindowTitle(_translate("addFC", "Add Fully Connected"))
        self.unitsLabel.setText(_translate("addFC", "units"))
        self.activationLabel.setText(_translate("addFC", "activation"))
        self.continueButton.setText(_translate("addFC", "确定"))
        self.cancelButton.setText(_translate("addFC", "取消"))
        activationList = ["sigmoid","relu","tanh","softmax"]
        self.activationComboBox.addItems(activationList)