# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'addFullConnect.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_addFC(object):
    def setupUi(self, addFC):
        addFC.setObjectName("addFC")
        addFC.resize(324, 231)
        self.label = QtWidgets.QLabel(addFC)
        self.label.setGeometry(QtCore.QRect(30, 60, 51, 16))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(addFC)
        self.label_2.setGeometry(QtCore.QRect(30, 100, 81, 16))
        self.label_2.setObjectName("label_2")
        self.lineEdit = QtWidgets.QLineEdit(addFC)
        self.lineEdit.setGeometry(QtCore.QRect(120, 60, 172, 21))
        self.lineEdit.setObjectName("lineEdit")
        self.comboBox_2 = QtWidgets.QComboBox(addFC)
        self.comboBox_2.setGeometry(QtCore.QRect(120, 100, 171, 22))
        self.comboBox_2.setEditable(False)
        self.comboBox_2.setCurrentText("")
        self.comboBox_2.setObjectName("comboBox_2")
        self.pushButton = QtWidgets.QPushButton(addFC)
        self.pushButton.setGeometry(QtCore.QRect(160, 160, 81, 31))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(addFC)
        self.pushButton_2.setGeometry(QtCore.QRect(60, 160, 81, 31))
        self.pushButton_2.setObjectName("pushButton_2")

        self.retranslateUi(addFC)
        QtCore.QMetaObject.connectSlotsByName(addFC)

    def retranslateUi(self, addFC):
        _translate = QtCore.QCoreApplication.translate
        addFC.setWindowTitle(_translate("addFC", "Add Fully Connected"))
        self.label.setText(_translate("addFC", "units"))
        self.label_2.setText(_translate("addFC", "activaton"))
        self.pushButton.setText(_translate("addFC", "确定"))
        self.pushButton_2.setText(_translate("addFC", "取消"))
