# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'addPooling.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_AddPooling(object):
    def setupUi(self, AddPooling):
        AddPooling.setObjectName("AddPooling")
        AddPooling.resize(328, 202)
        self.stridesLabel = QtWidgets.QLabel(AddPooling)
        self.stridesLabel.setGeometry(QtCore.QRect(50, 60, 71, 16))
        self.stridesLabel.setObjectName("stridesLabel")
        self.paddingLabel = QtWidgets.QLabel(AddPooling)
        self.paddingLabel.setGeometry(QtCore.QRect(50, 100, 71, 16))
        self.paddingLabel.setObjectName("paddingLabel")
        self.poolSizeEdit = QtWidgets.QLineEdit(AddPooling)
        self.poolSizeEdit.setGeometry(QtCore.QRect(120, 20, 172, 21))
        self.poolSizeEdit.setObjectName("poolSizeEdit")
        self.poolSizeLabel = QtWidgets.QLabel(AddPooling)
        self.poolSizeLabel.setGeometry(QtCore.QRect(30, 20, 91, 16))
        self.poolSizeLabel.setObjectName("poolSizeLabel")
        self.stridesEdit = QtWidgets.QLineEdit(AddPooling)
        self.stridesEdit.setGeometry(QtCore.QRect(120, 60, 172, 21))
        self.stridesEdit.setObjectName("stridesEdit")
        self.continueButton = QtWidgets.QPushButton(AddPooling)
        self.continueButton.setGeometry(QtCore.QRect(190, 150, 81, 31))
        self.continueButton.setObjectName("continueButton")
        self.cancelButton = QtWidgets.QPushButton(AddPooling)
        self.cancelButton.setGeometry(QtCore.QRect(50, 150, 81, 31))
        self.cancelButton.setObjectName("cancelButton")
        self.paddingComboBox = QtWidgets.QComboBox(AddPooling)
        self.paddingComboBox.setGeometry(QtCore.QRect(120, 100, 171, 23))
        self.paddingComboBox.setObjectName("paddingComboBox")

        self.retranslateUi(AddPooling)
        QtCore.QMetaObject.connectSlotsByName(AddPooling)

    def retranslateUi(self, AddPooling):
        _translate = QtCore.QCoreApplication.translate
        AddPooling.setWindowTitle(_translate("AddPooling", "Add Pooling"))
        self.stridesLabel.setText(_translate("AddPooling", "strides"))
        self.paddingLabel.setText(_translate("AddPooling", "padding"))
        self.poolSizeLabel.setText(_translate("AddPooling", "pool size"))
        self.continueButton.setText(_translate("AddPooling", "确定"))
        self.cancelButton.setText(_translate("AddPooling", "取消"))
        paddingList = ["VALID", "SAME"]
        self.paddingComboBox.addItems(paddingList)
