# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'addPooling.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_AddPooling(object):
    def setupUi(self, AddPooling):
        AddPooling.setObjectName("AddPooling")
        AddPooling.resize(328, 202)
        self.lineEdit_3 = QtWidgets.QLineEdit(AddPooling)
        self.lineEdit_3.setGeometry(QtCore.QRect(120, 94, 172, 21))
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.label_2 = QtWidgets.QLabel(AddPooling)
        self.label_2.setGeometry(QtCore.QRect(40, 66, 56, 16))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(AddPooling)
        self.label_3.setGeometry(QtCore.QRect(40, 96, 56, 16))
        self.label_3.setObjectName("label_3")
        self.lineEdit = QtWidgets.QLineEdit(AddPooling)
        self.lineEdit.setGeometry(QtCore.QRect(120, 30, 172, 21))
        self.lineEdit.setObjectName("lineEdit")
        self.label = QtWidgets.QLabel(AddPooling)
        self.label.setGeometry(QtCore.QRect(40, 30, 72, 16))
        self.label.setObjectName("label")
        self.lineEdit_2 = QtWidgets.QLineEdit(AddPooling)
        self.lineEdit_2.setGeometry(QtCore.QRect(120, 62, 172, 21))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.pushButton = QtWidgets.QPushButton(AddPooling)
        self.pushButton.setGeometry(QtCore.QRect(190, 150, 81, 31))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(AddPooling)
        self.pushButton_2.setGeometry(QtCore.QRect(50, 150, 81, 31))
        self.pushButton_2.setObjectName("pushButton_2")

        self.retranslateUi(AddPooling)
        QtCore.QMetaObject.connectSlotsByName(AddPooling)

    def retranslateUi(self, AddPooling):
        _translate = QtCore.QCoreApplication.translate
        AddPooling.setWindowTitle(_translate("AddPooling", "Add Pooling"))
        self.label_2.setText(_translate("AddPooling", "strides"))
        self.label_3.setText(_translate("AddPooling", "strides"))
        self.label.setText(_translate("AddPooling", "pool size"))
        self.pushButton.setText(_translate("AddPooling", "确定"))
        self.pushButton_2.setText(_translate("AddPooling", "取消"))
