# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'trainUD.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QMainWindow


class Ui_trainWD(QMainWindow):
    def setupUi(self, trainWD):
        trainWD.setObjectName("trainWD")
        trainWD.resize(823, 591)
        self.centralwidget = QtWidgets.QWidget(trainWD)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(480, 60, 131, 71))
        self.pushButton_2.setObjectName("pushButton_2")
        self.textBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser.setGeometry(QtCore.QRect(50, 180, 731, 361))
        self.textBrowser.setObjectName("textBrowser")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(20, 60, 71, 21))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(220, 60, 101, 21))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(220, 100, 71, 21))
        self.label_3.setObjectName("label_3")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(80, 60, 131, 20))
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_2.setGeometry(QtCore.QRect(310, 60, 113, 20))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_3.setGeometry(QtCore.QRect(310, 100, 113, 20))
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(420, 100, 21, 23))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(640, 60, 151, 71))
        self.pushButton_3.setObjectName("pushButton_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(20, 100, 71, 21))
        self.label_4.setObjectName("label_4")
        self.pushButton_4 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_4.setGeometry(QtCore.QRect(190, 100, 21, 23))
        self.pushButton_4.setObjectName("pushButton_4")
        self.lineEdit_4 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_4.setGeometry(QtCore.QRect(80, 100, 113, 20))
        self.lineEdit_4.setObjectName("lineEdit_4")
        trainWD.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(trainWD)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 823, 23))
        self.menubar.setObjectName("menubar")
        trainWD.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(trainWD)
        self.statusbar.setObjectName("statusbar")
        trainWD.setStatusBar(self.statusbar)

        self.retranslateUi(trainWD)
        QtCore.QMetaObject.connectSlotsByName(trainWD)

    def retranslateUi(self, trainWD):
        _translate = QtCore.QCoreApplication.translate
        trainWD.setWindowTitle(_translate("trainWD", "train"))
        self.pushButton_2.setText(_translate("trainWD", "train"))
        self.label.setText(_translate("trainWD", "epochs"))
        self.label_2.setText(_translate("trainWD", "batch size"))
        self.label_3.setText(_translate("trainWD", "dataset"))
        self.pushButton.setText(_translate("trainWD", "PushButton"))
        self.pushButton_3.setText(_translate("trainWD", "use model"))
        self.label_4.setText(_translate("trainWD", "model"))
        self.pushButton_4.setText(_translate("trainWD", "PushButton"))
