# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'trainWin.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QMainWindow


class Ui_trainWin(QMainWindow):
    def setupUi(self, trainWin):
        trainWin.setObjectName("trainWin")
        trainWin.resize(796, 591)
        self.centralwidget = QtWidgets.QWidget(trainWin)
        self.centralwidget.setObjectName("centralwidget")
        self.trainButton = QtWidgets.QPushButton(self.centralwidget)
        self.trainButton.setGeometry(QtCore.QRect(440, 50, 131, 71))
        self.trainButton.setObjectName("trainButton")
        self.epochsLabel = QtWidgets.QLabel(self.centralwidget)
        self.epochsLabel.setGeometry(QtCore.QRect(70, 40, 71, 21))
        self.epochsLabel.setObjectName("epochsLabel")
        self.batchLabel = QtWidgets.QLabel(self.centralwidget)
        self.batchLabel.setGeometry(QtCore.QRect(70, 80, 101, 21))
        self.batchLabel.setObjectName("batchLabel")
        self.datasetLabel = QtWidgets.QLabel(self.centralwidget)
        self.datasetLabel.setGeometry(QtCore.QRect(70, 120, 71, 21))
        self.datasetLabel.setObjectName("datasetLabel")
        self.epochLineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.epochLineEdit.setGeometry(QtCore.QRect(160, 40, 113, 20))
        self.epochLineEdit.setObjectName("epochLineEdit")
        self.batchLineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.batchLineEdit.setGeometry(QtCore.QRect(160, 80, 113, 20))
        self.batchLineEdit.setObjectName("batchLineEdit")
        self.datasetLineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.datasetLineEdit.setGeometry(QtCore.QRect(160, 120, 191, 20))
        self.datasetLineEdit.setObjectName("datasetLineEdit")
        self.openPathButton = QtWidgets.QPushButton(self.centralwidget)
        self.openPathButton.setGeometry(QtCore.QRect(350, 120, 21, 23))
        font = QtGui.QFont()
        font.setFamily("Adobe Devanagari")
        font.setPointSize(11)
        self.openPathButton.setFont(font)
        self.openPathButton.setObjectName("openPathButton")
        self.useModel = QtWidgets.QPushButton(self.centralwidget)
        self.useModel.setGeometry(QtCore.QRect(600, 50, 151, 71))
        self.useModel.setObjectName("useModel")
        self.trainScreen = QtWidgets.QTextEdit(self.centralwidget)
        self.trainScreen.setGeometry(QtCore.QRect(30, 170, 731, 361))
        self.trainScreen.setObjectName("trainScreen")
        trainWin.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(trainWin)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 796, 22))
        self.menubar.setObjectName("menubar")
        trainWin.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(trainWin)
        self.statusbar.setObjectName("statusbar")
        trainWin.setStatusBar(self.statusbar)

        self.retranslateUi(trainWin)
        QtCore.QMetaObject.connectSlotsByName(trainWin)

    def retranslateUi(self, trainWin):
        _translate = QtCore.QCoreApplication.translate
        trainWin.setWindowTitle(_translate("trainWin", "train"))
        self.trainButton.setText(_translate("trainWin", "train"))
        self.epochsLabel.setText(_translate("trainWin", "epochs"))
        self.batchLabel.setText(_translate("trainWin", "batch size"))
        self.datasetLabel.setText(_translate("trainWin", "dataset"))
        self.openPathButton.setText(_translate("trainWin", "..."))
        self.useModel.setText(_translate("trainWin", "use model"))
