# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'trainWin.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QMainWindow


class Ui_trainWin(QMainWindow):
    def setupUi(self, trainWin):
        trainWin.setObjectName("trainWin")
        trainWin.resize(796, 591)
        self.centralwidget = QtWidgets.QWidget(trainWin)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(440, 50, 131, 71))
        self.pushButton_2.setObjectName("pushButton_2")
        self.textBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser.setGeometry(QtCore.QRect(50, 180, 721, 361))
        self.textBrowser.setObjectName("textBrowser")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(70, 40, 71, 21))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(70, 80, 101, 21))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(70, 120, 71, 21))
        self.label_3.setObjectName("label_3")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(160, 40, 113, 20))
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_2.setGeometry(QtCore.QRect(160, 80, 113, 20))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_3.setGeometry(QtCore.QRect(160, 120, 113, 20))
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(270, 120, 21, 23))
        self.pushButton.setObjectName("pushButton")
        self.useModel = QtWidgets.QPushButton(self.centralwidget)
        self.useModel.setGeometry(QtCore.QRect(600, 50, 151, 71))
        self.useModel.setObjectName("useModel")
        trainWin.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(trainWin)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 796, 23))
        self.menubar.setObjectName("menubar")
        trainWin.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(trainWin)
        self.statusbar.setObjectName("statusbar")
        trainWin.setStatusBar(self.statusbar)

        self.retranslateUi(trainWin)
        QtCore.QMetaObject.connectSlotsByName(trainWin)

    def retranslateUi(self, trainWin):
        _translate = QtCore.QCoreApplication.translate
        trainWin.setWindowTitle(_translate("trainWin", "train"))
        self.pushButton_2.setText(_translate("trainWin", "train"))
        self.label.setText(_translate("trainWin", "epochs"))
        self.label_2.setText(_translate("trainWin", "batch size"))
        self.label_3.setText(_translate("trainWin", "dataset"))
        self.pushButton.setText(_translate("trainWin", "PushButton"))
        self.useModel.setText(_translate("trainWin", "use model"))
