# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'useModel.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets

from PyQt5.QtWidgets import QMainWindow


class Ui_testModel(QMainWindow):
    def setupUi(self, testModel):
        testModel.setObjectName("testModel")
        testModel.resize(1019, 603)
        self.centralwidget = QtWidgets.QWidget(testModel)
        self.centralwidget.setObjectName("centralwidget")
        self.cameraScreen = QtWidgets.QLabel(self.centralwidget)
        self.cameraScreen.setGeometry(QtCore.QRect(20, 40, 711, 451))
        self.cameraScreen.setAlignment(QtCore.Qt.AlignCenter)
        self.cameraScreen.setObjectName("cameraScreen")
        self.startButton = QtWidgets.QPushButton(self.centralwidget)
        self.startButton.setGeometry(QtCore.QRect(790, 70, 161, 61))
        self.startButton.setObjectName("startButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(790, 150, 161, 61))
        self.pushButton_2.setObjectName("pushButton_2")
        self.resultLabel = QtWidgets.QLabel(self.centralwidget)
        self.resultLabel.setGeometry(QtCore.QRect(770, 320, 54, 12))
        self.resultLabel.setObjectName("resultLabel")
        self.resultEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.resultEdit.setGeometry(QtCore.QRect(770, 340, 221, 201))
        self.resultEdit.setObjectName("resultEdit")
        testModel.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(testModel)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1019, 22))
        self.menubar.setObjectName("menubar")
        testModel.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(testModel)
        self.statusbar.setObjectName("statusbar")
        testModel.setStatusBar(self.statusbar)

        self.retranslateUi(testModel)
        QtCore.QMetaObject.connectSlotsByName(testModel)

    def retranslateUi(self, testModel):
        _translate = QtCore.QCoreApplication.translate
        testModel.setWindowTitle(_translate("testModel", "test model"))
        self.cameraScreen.setText(_translate("testModel", "摄像头画面"))
        self.startButton.setText(_translate("testModel", "start"))
        self.pushButton_2.setText(_translate("testModel", "stop"))
        self.resultLabel.setText(_translate("testModel", "result"))
