# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'useModel.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QMainWindow


class Ui_testModel(QMainWindow):
    def setupUi(self, testModel):
        testModel.setObjectName("testModel")
        testModel.resize(1019, 603)
        self.centralwidget = QtWidgets.QWidget(testModel)
        self.centralwidget.setObjectName("centralwidget")
        self.cameraScreen = QtWidgets.QLabel(self.centralwidget)
        self.cameraScreen.setGeometry(QtCore.QRect(20, 40, 711, 451))
        self.cameraScreen.setAlignment(QtCore.Qt.AlignCenter)
        self.cameraScreen.setObjectName("cameraScreen")
        self.startButton = QtWidgets.QPushButton(self.centralwidget)
        self.startButton.setGeometry(QtCore.QRect(790, 40, 161, 61))
        self.startButton.setObjectName("startButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(790, 120, 161, 61))
        self.pushButton_2.setObjectName("pushButton_2")
        self.resultLabel = QtWidgets.QLabel(self.centralwidget)
        self.resultLabel.setGeometry(QtCore.QRect(770, 320, 71, 16))
        self.resultLabel.setObjectName("resultLabel")
        self.resultEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.resultEdit.setGeometry(QtCore.QRect(770, 340, 221, 201))
        self.resultEdit.setObjectName("resultEdit")
        self.xlabel = QtWidgets.QLabel(self.centralwidget)
        self.xlabel.setGeometry(QtCore.QRect(850, 220, 16, 16))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(11)
        self.xlabel.setFont(font)
        self.xlabel.setObjectName("xlabel")
        self.ylabel_3 = QtWidgets.QLabel(self.centralwidget)
        self.ylabel_3.setGeometry(QtCore.QRect(850, 250, 16, 16))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(11)
        self.ylabel_3.setFont(font)
        self.ylabel_3.setObjectName("ylabel_3")
        self.inputShaplabel = QtWidgets.QLabel(self.centralwidget)
        self.inputShaplabel.setGeometry(QtCore.QRect(770, 200, 81, 16))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(11)
        self.inputShaplabel.setFont(font)
        self.inputShaplabel.setObjectName("inputShaplabel")
        self.zlineEdit_3 = QtWidgets.QLineEdit(self.centralwidget)
        self.zlineEdit_3.setGeometry(QtCore.QRect(870, 280, 113, 20))
        self.zlineEdit_3.setObjectName("zlineEdit_3")
        self.ylineEdit_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.ylineEdit_2.setGeometry(QtCore.QRect(870, 250, 113, 20))
        self.ylineEdit_2.setObjectName("ylineEdit_2")
        self.zlabel_4 = QtWidgets.QLabel(self.centralwidget)
        self.zlabel_4.setGeometry(QtCore.QRect(850, 280, 16, 16))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(11)
        self.zlabel_4.setFont(font)
        self.zlabel_4.setObjectName("zlabel_4")
        self.xlineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.xlineEdit.setGeometry(QtCore.QRect(870, 220, 113, 20))
        self.xlineEdit.setObjectName("xlineEdit")
        self.picEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.picEdit.setGeometry(QtCore.QRect(70, 510, 461, 20))
        self.picEdit.setObjectName("picEdit")
        self.uploadButton = QtWidgets.QPushButton(self.centralwidget)
        self.uploadButton.setGeometry(QtCore.QRect(530, 510, 141, 26))
        self.uploadButton.setObjectName("uploadButton")
        testModel.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(testModel)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1019, 22))
        self.menubar.setObjectName("menubar")
        testModel.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(testModel)
        self.statusbar.setObjectName("statusbar")
        testModel.setStatusBar(self.statusbar)

        self.retranslateUi(testModel)
        QtCore.QMetaObject.connectSlotsByName(testModel)

    def retranslateUi(self, testModel):
        _translate = QtCore.QCoreApplication.translate
        testModel.setWindowTitle(_translate("testModel", "test model"))
        self.cameraScreen.setText(_translate("testModel", "摄像头画面"))
        self.startButton.setText(_translate("testModel", "start"))
        self.pushButton_2.setText(_translate("testModel", "stop"))
        self.resultLabel.setText(_translate("testModel", "result:"))
        self.xlabel.setText(_translate("testModel", "x"))
        self.ylabel_3.setText(_translate("testModel", "y"))
        self.inputShaplabel.setText(_translate("testModel", "input shape："))
        self.zlabel_4.setText(_translate("testModel", "z"))
        self.uploadButton.setText(_translate("testModel", "upload"))
