# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'useModel.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QMainWindow


class Ui_testModel(QMainWindow):
    def setupUi(self, testModel):
        testModel.setObjectName("testModel")
        testModel.resize(1019, 603)
        self.centralwidget = QtWidgets.QWidget(testModel)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(20, 40, 711, 451))
        self.label.setObjectName("label")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(790, 70, 161, 61))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(790, 150, 161, 61))
        self.pushButton_2.setObjectName("pushButton_2")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(770, 320, 54, 12))
        self.label_2.setObjectName("label_2")
        self.textBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser.setGeometry(QtCore.QRect(770, 340, 221, 181))
        self.textBrowser.setObjectName("textBrowser")
        testModel.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(testModel)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1019, 23))
        self.menubar.setObjectName("menubar")
        testModel.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(testModel)
        self.statusbar.setObjectName("statusbar")
        testModel.setStatusBar(self.statusbar)

        self.retranslateUi(testModel)
        QtCore.QMetaObject.connectSlotsByName(testModel)

    def retranslateUi(self, testModel):
        _translate = QtCore.QCoreApplication.translate
        testModel.setWindowTitle(_translate("testModel", "test model"))
        self.label.setText(_translate("testModel", "摄像头画面"))
        self.pushButton.setText(_translate("testModel", "start"))
        self.pushButton_2.setText(_translate("testModel", "stop"))
        self.label_2.setText(_translate("testModel", "result"))
